#! /bin/sh #-f
export RASPA_DIR=${HOME}/RASPA/simulations/
export DYLD_LIBRARY_PATH=${RASPA_DIR}/lib
export LD_LIBRARY_PATH=${RASPA_DIR}/lib

# remove calculation folders
rm -rf RestartInitial                                                                                    
rm -rf CrashRestart
rm -rf Movies
rm -rf Output
rm -rf VTK
rm -rf Restart

# run initial simulation
awk '!found && /^RestartFile/ {print "#" $0; found=1; next} {print}' simulation.input > temp && mv temp simulation.input 
awk '!found && /^#CreateNumberOfMolecules/ {sub(/^#/, ""); found=1} {print}' simulation.input > temp && mv temp simulation.input    
$RASPA_DIR/bin/simulate $1 > /dev/null 2>&1

# remove output files so they dont get interpreted as results if the 2nd simulation (restart) fails
#rm -r Output/System_0/* # (the output of this initial simulation is random as the adsorbate is placed randomly)
rm -rf Output

# copy restart file
cp -r Restart RestartInitial/

# delete (random) position of adsorbate created in initial simulation
sed -i '' '/^Adsorbate-atom/d' RestartInitial/System_0/*
# add desired adsorbate position to restart file
#echo "Adsorbate-atom-position:  0 0 4.56 0.0 0.0" >> RestartInitial/System_0/* # hard coded
echo "Adsorbate-atom-position:  0 0 0.0 0.0 0.0" >> RestartInitial/System_0/* # hard coded


# restart simulation
awk '!found && /^#RestartFile/ {sub(/^#/, ""); found=1} {print}' simulation.input > temp && mv temp simulation.input    
awk '!found && /^CreateNumberOfMolecules/ {print "#" $0; found=1; next} {print}' simulation.input > temp && mv temp simulation.input    
$RASPA_DIR/bin/simulate $1 > /dev/null 2>&1

# check if Output dir exists:
if [ ! -d "Output/System_0" ]; then
    echo "Error: Output directory not found. maybe simulations (restart) failed" >&2 # to stderr
    exit 1
fi

# print energy results:
grep -m1 -A4 "Host/Adsorbate energy:" Output/System_0/*
#grep -m1 "Alpha convergence parameter" Output/System_0/* # prints the alpha/kappa/smearing cooefficient RASPA used for the calculation
